[package]
name = "hikari-sentinel"
version = "0.1.0"
authors = ["ibochivincent-lang <ibochivincent-lang@users.noreply.github.com>"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["lib"]

[dependencies]
soroban-sdk = { workspace = true }
interfaces = { package = "hikari-interfaces", path = "../interfaces" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
